CREATE ROLE kave_owner
  NOLOGIN NOINHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE
  NOREPLICATION NOBYPASSRLS;

CREATE ROLE kave_runtime
  LOGIN NOINHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE
  NOREPLICATION NOBYPASSRLS;

GRANT CREATE ON DATABASE kave TO kave_owner;
GRANT CONNECT ON DATABASE kave TO kave_runtime;
GRANT kave_owner TO postgres;
