FROM golang:1.26.1-alpine3.22

RUN apk add --no-cache \
    bash \
    ca-certificates \
    git \
    make

RUN go install github.com/bufbuild/buf/cmd/buf@v1.56.0 && \
    cp /go/bin/buf /usr/local/bin/

RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.36.11 && \
    go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.5.1 && \
    cp /go/bin/protoc-gen-go /go/bin/protoc-gen-go-grpc /usr/local/bin/

WORKDIR /workspace

CMD ["buf", "--help"]
