apiVersion: kave.io/v1
kind: KaveConfig

daemon:
  address: 0.0.0.0:19090
  proxy_address: 0.0.0.0:18081
  data_dir: /data
  log_level: info
  log_format: json

server:
  addr: 0.0.0.0:18080

grpc:
  addr: 0.0.0.0:19090

postgres:
  host: ${KAVE_POSTGRES_HOST}
  port: ${KAVE_POSTGRES_PORT}
  user: ${KAVE_POSTGRES_USER}
  password: ${KAVE_POSTGRES_PASSWORD}
  dbname: ${KAVE_POSTGRES_DBNAME}
  sslmode: ${KAVE_POSTGRES_SSLMODE}

storage:
  defaults:
    app:
      kind: postgres
    span:
      kind: duckdb
      path: /data/spans.duckdb
